### ISSUE TITLE
Use a .bibtex bibliography

### ISSUE THREAD

**Issue by jepusto** [meghapsimatrix/simhelpers#8]
Given that the vignettes include a lot of citations, and the references are similar across different vignettes, it might be good to version control the citations with a .bibtext bibliography. Then the vignettes and README could use [automatic citation references](https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html). 

Right now the Morris et al. paper is cited as (2018), but the reference listed is actually 2019. Using the automatic citation references would make it easy to correct this.

**Comment by meghapsimatrix** [comment]
I did automatic citation but it gives me a note for the README:
![image](https://user-images.githubusercontent.com/33493716/77586510-55bf7200-6eb4-11ea-8bc1-f4bc9304648f.png)

Good thing you pointed this out because I had peoples' first names as their last names 🤕 🤒 

I will keep editing to clean up any messes. Thanks so much!!!

**Comment by jepusto** [comment]
It's probably worth doing a little bit of googling or tweeting to figure
out where to put the csl and bibliography files in a package. Others have
surely had the same problem.

**Comment by meghapsimatrix** [comment]
I think I am going to do manual citation just for README because the pkgdown home page ref section looks like this with the automatic citation: 

![image](https://user-images.githubusercontent.com/33493716/77587442-e480be80-6eb5-11ea-89f4-411f299be884.png)

But, on the README thing on GitHub rep page for simhelpers, the citations look fine. Also adding the citations to README created a _main.Rmd file and a libs file which I am pretty sure wasn't there before. When I do manual citation for README, I don't get any notes when I do CMD check. 

The vignette citations are fine though. I have citations and csl stuff in vignettes folder right now. I will do some exploring about citations stuff for packages. Or I might just be like whatevs donkeys [@lucy] 😺

**Comment by jepusto** [comment]
Makes sense. I fully support the WED approach.
